<a href="https://colab.research.google.com/github/AyozeGS/IABD/blob/main/7RO/UT1/T2/7RO_AG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TAREA ALGORITMOS EVOLUTIVOS PROGRAMACIÓN EN IA
**EL PROBLEMA DEL VIAJANTE DE COMERCIO**

Crea un programa en Python que resuelva el problema para al menos 5 poblaciones (por ejemplo Telde, Gáldar, etc) usando el algoritmo evolutivo cuyas funciones de mutación y de recombinación vienen descritas en https://www.youtube.com/watch?v=3Kzj2FNaua8

**ENLACES DE INTERÉS:**

https://pythondiario.com/2018/05/el-problema-de-las-n-reinas-algoritmos.html

https://jarroba.com/algoritmos-geneticos-ejemplo

https://es.wikipedia.org/wiki/Problema_del_viajante

**RÚBRICA:**



*   (4 Puntos) El algoritmo muestra soluciones aceptables (para ello usa distancias reales en la matriz de distancias)
*   (4 Puntos) Se crean y comentan los métodos de mutación, fitness, y recombinanción.
*   (2 Puntos) Uso del vocabulario correcto (población, generación etc) así como explicación de los hiperparámetos (probabilidad de recombinación, de mutación, población inicial etc).

Se subirá un archivo PDF con el notebook de Jupiter incluyendo la ejecución y los markdown con las explicaciones.

In [ ]:
import pandas as pd
import numpy as np
import random

#Load file and clean data
df = pd.read_csv("data_municipios.csv", index_col=0)
df[df.isna()] = 0
display(df)

Las Palmas  Telde  Arucas  Galdar  Teror  Agaete  Mogan
Distancia(km)                                                         
Las Palmas            0.0   15.0     9.0    22.0   13.0    26.0   39.0
Telde                15.0    0.0    17.0    28.0   15.0    30.0   33.0
Arucas                9.0   17.0     0.0    13.0    7.0    18.0   33.0
Galdar               22.0   28.0    13.0     0.0   14.0     7.0   30.0
Teror                13.0   15.0     7.0    14.0    0.0    16.0   26.0
Agaete               26.0   30.0    18.0     7.0   16.0     0.0   24.0
Mogan                39.0   33.0    33.0    30.0   26.0    24.0    0.0

### Functions

In [ ]:
# Fitness: function to evaluate solution. It uses sum of distances
def fitness(member):

  sum = 0
  for i in range(len(member)-1):
    sum += df.iloc[member[i]][member[i+1]]
  population_total_dist.append(sum)

  return sum

In [ ]:
# Mutation: function to apply a little change in a member in order to create other
def mutation(member):

  # Get 2 randoms index for exchange their values
  mutated_member = np.copy(member)
  mutated_index_1 = random.randint(1, len(n_population))
  mutated_index_2 = random.randint(1, len(n_population))
  while mutated_index_2 != mutated_index_1:
    mutated_index_2 = random.randint(1, len(n_population))

  # Exchange values
  mutated_member[mutated_index_1] = member[mutated_index_2]
  mutated_member[mutated_index_2] = member[mutated_index_1]

  return mutated_member

In [ ]:
# Recombination : function to combine two members in order to create a new one
def recombination(member1, member2):

  recombinated_member = np.copy(member1)

  for i in recombinated_member(len):
    recombinated_member[i] = member2[member1[i]]

  return recombinated_member

## Params

In [ ]:
# Distances matrix
distances = df.to_numpy(dtype=int)
# Strings array for municipalities
municipalities = df.index.to_numpy()
# Integers array for municipalities
indexes = np.array(range(len(municipalities)))

#hyperparameters
n_generations = 20
n_population = 10
n_chromosomes = len(municipalities)
prob_recombination = 0.2
prob_mutation = 0.6

#vars
population = []
population_total_dist = []

### First Population

In [ ]:
population.clear()
population_total_dist.clear()

#Generate N random vectors from indexes. Ex: [4 0 5 2 6 1 3]
while len(population) < n_population:
  #member = np.copy(indexes)
  #np.random.shuffle(member)
  member = np.random.permutation(indexes)
  #Check if member already in population
  if not population or not (member == population).all(axis=1).any():
    population.append(member)

print(np.array(population))

#Calculate total distance for each member and save in an array
for member in population:
  sum = 0
  for i in range(len(member)-1):
    sum += df.iloc[member[i]][member[i+1]]
  population_total_dist.append(sum)


[[2 5 1 3 0 4 6]
 [5 3 2 1 4 6 0]
 [1 6 3 0 4 5 2]
 [2 5 6 0 3 4 1]
 [5 1 3 4 0 2 6]
 [1 5 6 3 4 2 0]
 [1 3 4 6 0 2 5]
 [0 5 4 1 3 2 6]
 [3 0 1 2 6 5 4]
 [2 5 3 6 1 4 0]]


In [ ]:
population_total_dist = [fitness(member) for member in population]

print(population_total_dist)
print("distancia minima:", min(population_total_dist), "km.")

min_index = population_total_dist.index(min(population_total_dist))
#for i in population[min_index]:
#  print(df.index[i])

print(population[min_index])
print([df.index[i] for i in population[min_index]])

[137.0, 117.0, 132.0, 132.0, 127.0, 114.0, 134.0, 131.0, 127.0, 116.0]
distancia minima: 114.0 km.
[1 5 6 3 4 2 0]
['Telde', 'Agaete', 'Mogan', 'Galdar', 'Teror', 'Arucas', 'Las Palmas']


In [ ]:
#Prueba de vector coincidiendo con fila de array
a = np.array([[5, 6, 3, 2, 1, 4, 0],
 [6, 5, 3, 4, 1, 0, 2],
 [5, 4, 1, 0, 3, 6, 2],
 [0, 3, 1, 4, 2, 6, 5],
 [0, 1, 4, 3, 6, 5, 2],
 [3, 2, 5, 6, 1, 0, 4],
 [3, 2, 6, 0, 4, 1, 5],
 [2, 0, 1, 4, 5, 6, 3],
 [1, 4, 2, 3, 0, 6, 5],
 [2, 1, 3, 4, 6, 5, 0]])
b = np.array([3, 2, 5, 6, 0, 1, 4])
c = np.array([3, 2, 5, 6, 1, 0, 4])

#print(np.any(member == np.all(population)))
print((a == b).all(axis=1))
print((a == b).all(axis=1).any())
print((a == c).all(axis=1))
print((a == c).all(axis=1).any())
print((a == c).all(axis=1).tolist().index(True))

[False False False False False False False False False False]
False
[False False False False False  True False False False False]
True
5
